name: my-check
on: push
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v7
      # Устанавливаем Node.js
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: 'npm' # ускоряет повторные сборки
      # Ставим зависимости
      - run: make install
      # Запуск lint
      - name: run lint
        run: make lint
      # Запуск тестов c покрытием
      - name: test and coverage
        run: make test-coverage
      # Запуск SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=frontend-project-46/coverage/lcov.info.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}