name: my-check
on: 
  push:
    branches:
      - main
pull_request:
  types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v7
      # Устанавливаем Node.js
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: 'npm' # ускоряет повторные сборки
      # Ставим зависимости
      - run: npm install
      # Запуск lint
      - name: run lint
        run: make lint
      # Запуск тестов
      # - name: run tests
      #   run: make test
      # Запуск тестов c покрытием
      - name: test and coverage
        run: make test-coverage
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}